sqlite3:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

development:
  adapter: mysql
  database: minds
  username: root
  host: localhost
