sqlite3:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: mysql
  database: systeminds
  username: systeminds
  password: 1234qwerasdfzxcv
  host: mysql.qi64.com

development:
  adapter: mysql
  database: minds
  username: root
  host: localhost
