development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 1000

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: sqlite3
  database: db/production.sqlite3
  timeout: 1000
