sqlite3:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 1000

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: mysql
  database: debian
  username: root
  host: 192.168.1.2

mysql:
  adapter: mysql
  database: debian
  username: root
  host: 192.168.1.2
