test:
  adapter: mysql
  database: minds_test
  username: root
  password: secret
  host: localhost

development:
  adapter: mysql
  database: minds_development
  username: root
  password: secret
  host: localhost
