all:
    inject_view: true
    stack_trace_lines: 3
    trace_includes_vendor: false
    trace_includes_lib: true
    profiling: enabled
    production_data: true
    max_safe_key_length: 100

    warn_severity: 3
    critical_severity: 7

    warn_query_count: 5
    critical_query_count: 10

    warn_duration_threshold: 0.1
    critical_duration_threshold: 0.4

development:
    enabled: true

mysql:
  enabled: true

sqlite3:
  enabled: true

production:
    enabled: false

test:
    enabled: false
